const products = [
    {
        id: '1',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '2',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '3',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '4',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '5',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '6',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '7',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '8',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '9',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    },
    {
        id: '10',
        name: '',
        price: 1000,
        category: '',
        img: '',
        stock: 10,
        description: '',
    }
]